### ISSUE TITLE
is support GitHub Flavored Markdown Spec ?

### ISSUE THREAD

**Issue by find456789** [miyuchina/mistletoe#104]
https://github.github.com/gfm/

**Comment by pbodnar** [comment]
Well, you may use `GithubWikiRenderer` (https://github.com/miyuchina/mistletoe/blob/master/contrib/github_wiki.py) that supports GitHub wiki-style links (i. e. `[[title | target]]`). But this doesn't seem to be a part of the GFM spec. Anyway, how to identify all the possible differences of mistletoe from GFM? Ideas?

**Comment by pbodnar** [comment]
@averms, thanks for your tip, although I'm not quite sure how to grasp this - do you?

Anyway, I think it would come generally handy to have at least a manually-prepared list of features / specs implemented by mistletoe? Or something like a classical "comparison with other tools" table...
