### ISSUE TITLE
Bug in table rendering with code blocks.

### ISSUE THREAD

**Issue by bumbread** [miyuchina/mistletoe#107]
The rendering of the following markdown table is incorrect.
```
| Sign | Name
|---|---|
| `&` | ampersand |
| `|` | pipe |
```
The library interprets the pipe symbol as being the table column separator.

**Comment by huettenhain** [comment]
This might be a duplicate / related to #85, but it is my impression that mistletoe might be abandoned. At the time of writing, I would suggest to check out [mistune](https://pypi.org/project/mistune/) which seem to be actively maintained; there are a few projects of mine that I am planning to port from mistletoe to mistune in the near future.

**Comment by pbodnar** [comment]
Yes, I'm closing this as duplicate, thank you for reporting it anyway. :)

**Comment by huettenhain** [comment]
Boy, am I happy to see activity here. ❤️
