### ISSUE TITLE
duplicate files docs/CONTRIBUTING.html and docs/contributing.html

### ISSUE THREAD

**Issue by gvwilson** [miyuchina/mistletoe#127]
When cloning the repo on MacOS I get a warning:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/CONTRIBUTING.html'
  'docs/contributing.html'
```

**Comment by gvwilson** [comment]
Thanks @pbodnar - much appreciated. Are you doing most of the maintenance these days?

**Comment by pbodnar** [comment]
> Thanks @pbodnar - much appreciated. Are you doing most of the maintenance these days?

Yes, I do, I was given contributor rights by Mi Yu some time ago. I mostly do some minor updates or merge PRs when I have time and when in a good mood... :) So, contributions are welcome, but I cannot guarantee when I will get to them...

**Comment by pbodnar** [comment]
OK, so I have removed the extra "docs/CONTRIBUTING.html" file and added a README file with a deprecation note. I guess that this could suffice for now.
