### ISSUE TITLE
Make tables GFM-compliant - support less than 3 dashes in delimiters

### ISSUE THREAD

**Issue by not-my-profile** [miyuchina/mistletoe#131]
As per the specification for [GitHub flavored Markdown](https://github.github.com/gfm/#tables-extension-) (GFM) the following markdown

```
| foo |
|-|
| bar|
```

should be rendered as a table:

| foo |
|-|
| bar|

However mistletoe does not do so since it expects at least three dashes:

https://github.com/miyuchina/mistletoe/blob/8447a42ffa9b83cd55b05b206e36113592723248/mistletoe/block_token.py#L643

It would probably be a good idea to ensure that mistletoe passes all 8 test cases defined in the GFM table specification.

**Comment by pbodnar** [comment]
@not-my-profile, thanks for your report. This seems to make sense.

I have quickly checked and historically _GFM_ required 3 dashes (or "hyphens") in delimiters as well, but this has changed when #/github/markup/issues/371 was implemented (it is unclear when exactly that happened). And for example _kramdown_ is also happy with just 1 dash.

So I guess we can do this. The minimum of 3 dashes is checked in several places in the code and we should also double-check that something else won't get broken.
