### ISSUE TITLE
**`what`:** gives odd output

### ISSUE THREAD

**Issue by greg-minshall** [miyuchina/mistletoe#138]
addmittedly
````
**`what`:**
````
is an odd input.  but, mistletoe's output is
````
<p>**<code>what</code>:**</p>\n
````
while commonmark's dingus' output is
````
<p><strong><code>what</code>:</strong></p>
````

**Comment by pbodnar** [comment]
Hi @greg-minshall, It looks like this kind of problem was fixed in [v0.8.2](https://github.com/miyuchina/mistletoe/releases/tag/v0.8.2) (see #70). Maybe you use an older version?

**Comment by greg-minshall** [comment]
yes.  v.0.8.1.  (current, at least as of a day or so ago, on arch "aur".)  thanks!

**Comment by pbodnar** [comment]
OK, so hopefully v0.8.2 from https://pypi.org/project/mistletoe/ will arrive into the AUR soon as well. :) I guess the community around Arch Linux manages that update process, somehow...
