### ISSUE TITLE
FootnoteLink removing trailing spaces

### ISSUE THREAD

**Issue by huettenhain** [miyuchina/mistletoe#14]
First of all, this is a great project and incidentally it offers the only way to have a decent Markdown to Jira converter. I encountered one tiny bug in the converter:

Assume the following markdown document:

    Test [link] will remove space.

    [link]: http://www.nullteilerfrei.de/

Then the output of `md2jira` will be the following:

    Test [link|http://www.nullteilerfrei.de/]will remove space.

As you can see, there should be a space right after the link.

**Comment by miyuchina** [comment]
Hi there! Thanks for the interest!

Jira renderer support was just added yesterday, and as you can probably tell by the code, it's not yet production ready. I'll cc the author @cctile to see if they have any idea what's going on, and I'll try to take a look once I free myself from work as well.

Wow, I had no idea there's no adequate Markdown to Jira converter..

**Comment by huettenhain** [comment]
Thanks for the quick turnaround! I will be as patient as I am eager for this tool =). 

To elaborate: I might be picky with what an "adequate" converter is, but I was looking for something that I works from the command line. And added bonus is that I might integrate this directly in my scripts that communicate with Jira's REST(-like) API. Most importantly however, I am lucky enough not to be in the business of running node.js and I really want to keep it that way.

**Comment by cctile** [comment]
Took a look at https://github.com/cctile/mistletoe/blob/dev/plugins/jira_renderer.py#L88
See two ways to fix this for `render_footnote_link`:

1. Quick and dirty where we introduce end space in `template`:
```
template = '[{inner}|{target}] '
```
2. Push fix on @miyuchina where the space is honored in the AST level. 

@miyuchina your thoughts?

**Comment by cctile** [comment]
Also @huettenhain thanks for trying this out! Appreciate your feedback!

**Comment by miyuchina** [comment]
Should be fixed in f73e3f1. Closing for now.
