### ISSUE TITLE
Unused imports

### ISSUE THREAD

**Issue by TheSecEng** [miyuchina/mistletoe#146]
Just looked at the Jira renderer and noticed that. the following are unused imports

https://github.com/miyuchina/mistletoe/blob/94022647cd9d80e242db5c93a6567e3155b468bc/contrib/jira_renderer.py#L24

https://github.com/miyuchina/mistletoe/blob/94022647cd9d80e242db5c93a6567e3155b468bc/contrib/jira_renderer.py#L29

**Comment by pbodnar** [comment]
@TheSecEng, thanks for pointing that out.

I've created PR #147 for the case you or others would like to check the cleanup made. I think I will leave it open like for a week and then merge it if no one will protest. :)
