### ISSUE TITLE
CommonMark compliance

### ISSUE THREAD

**Issue by miyuchina** [miyuchina/mistletoe#17]
## Rationale

Starting from version 0.5, mistletoe will be striving towards spec compliance with [CommonMark](https://commonmark.org). If you have issues / pull requests regarding CommonMark compliance, I'd be happy to review them in a new thread.

I'm hoping spec compliance would give mistletoe more predictable behavior, and help stabilize the interface.

This issue will be used as a place for progress reports and meta-discussions. Once mistletoe starts passing more test cases, I'll add further documentations to record which tests are failing or ignored. All relevant links should be expected to appear in this issue; if I'm missing one, please comment below!

## Drawbacks

John Gruber, the original author of Markdown, had a few qualms with CommonMark. Discussions can be found on the CommonMark forum [here](https://talk.commonmark.org/t/standard-markdown-is-now-commonmark/434). Here are my personal concerns about pushing for spec compliance:

1. CommonMark is strongly defined, whereas mistletoe wants to be flexible in its implementation, where users can influence the parsing and rendering process as much as they want.

2. CommonMark has a limited functionality set, whereas mistletoe follows the rule of "sane defaults," and generally wants to support [GitHub Flavored Markdown](https://github.github.com/gfm/) as well. Tables in pure Markdown, for example, are not supported in CommonMark, but are supported in mistletoe.

3. To comply with the spec, CommonMark might impose implementation restrictions. I've had an unfounded suspicion that to pass all the test cases, one would have to more or less stick to the reference implementation, or the parsing strategy outlined in the appendix. This would, again, mean less flexibility for the users.

Due to reasons above, mistletoe might not achieve a 100% compliance with CommonMark, though it is still possible. In future versions I will still value flexibility over compliance. Divergence from the spec will be documented.

## Test suite

A list of CommonMark specs, including the latest release, can be found [here](http://spec.commonmark.org). I will be pulling a test suite from CommonMark's [GitHub repo](https://github.com/commonmark/CommonMark). Assuming you are in `test/commonmark` directory:

* `commonmark.json` is the current test suite mistletoe is testing itself against, in JSON format;
* running `python3 commonmark.py` tests mistletoe against `commonmark.json`, printing out failed test cases and a total count;
* running `./spec.sh` pulls down the latest test suite from CommonMark's repository.

The test suite might not be up-to-date. Let me know if so!

## Miscellaneous

Relevant [xkcd](https://xkcd.com/927/).

**Comment by cctile** [comment]
Thanks much for working on this! Any ideas on when the next release will be?

**Comment by miyuchina** [comment]
Sorry, life finally caught up with me in the past week. I did a minor version release just now!

**Comment by miyuchina** [comment]
mistletoe version 0.6 implemented Commonmark compliant lists!

**Comment by miyuchina** [comment]
All tests passing as of commit 182c29f.
