### ISSUE TITLE
wrong result 

### ISSUE THREAD

**Issue by redstoneleo** [miyuchina/mistletoe#175]
```
s1=r'''**[Usage](http://127.0.0.1:8000/cms/pages/82/edit/)**：'''
import mistletoe
from mistletoe import Document, HTMLRenderer
rendered = mistletoe.markdown(s1, HTMLRenderer)
print(rendered)
```

output:
`<p>**<a href="http://127.0.0.1:8000/cms/pages/82/edit/">Usage</a>**：</p>`
the correct should be :
`<p><strong><a href="http://127.0.0.1:8000/cms/pages/82/edit/">Usage</a></strong>：</p>`

**Comment by pbodnar** [comment]
@redstoneleo, thanks for the report. Luckily, this issue is already fixed in the master - by 0c05dcda471719f0400db763b0f584d710350766 within #96.

Details: This problem occurred only when using the special char of `：` instead of the more common `: ` (2 chars).
