### ISSUE TITLE
Question how to modify ast and write back out as markdown

### ISSUE THREAD

**Issue by tvmaly** [miyuchina/mistletoe#178]
Could you add an example on how to take an AST of the markdown, modify it then write out the result to markdown?

**Comment by pbodnar** [comment]
@SomeoneSerge is correct. I.e. right now, there is no `MarkdownRenderer`, but it is being worked on (namely in #162).

@tvmaly, I hope that this answers your question. :)

**Comment by codekiln** [comment]
Now that we have `MarkdownRenderer` class it would be nice if there were some instructions on how to use it to render a document fragment. If we have a `mistletoe.block_token.Document` with 31 children, how can we use `MarkdownRenderer` to render it?

**Comment by pbodnar** [comment]
@codekiln, thanks for the update. Some more info then:

1) The thing is one can use `MarkdownRenderer` as any other renderer in mistletoe. While of course, it has got special options like `max_line_length` which can be passed to the constructor (see its [pydoc](https://github.com/miyuchina/mistletoe/blob/v1.3.0/mistletoe/markdown_renderer.py#L102)).

2) Also note that there is this dedicated [Markdown to Markdown parsing-and-rendering](https://github.com/miyuchina/mistletoe/blob/v1.3.0/dev-guide.md#markdown-to-markdown-parsing-and-rendering) chapter available in the Developer's Guide, which shows how to modify the AST before rendering it back to markdown.
