### ISSUE TITLE
Use strict PascalCase for class names

### ISSUE THREAD

**Issue by pbodnar** [miyuchina/mistletoe#182]
The historically used "lenient" usage of the PascalCase (pascal case) convention in mistletoe is quite impractical when it comes to introducing more complex names. I suggest here to use the _strict_ variant which doesn't have this problem and leads to a more consistent code base.

E.g. change `HTMLRenderer` to `HtmlRenderer`, `HTMLBlock` to `HtmlBlock`.

For backwards compatibility, we can introduce aliases for the old names, marking them as deprecated.

**Comment by pbodnar** [comment]
CC @anderskaplan.

**Comment by pydsigner** [comment]
Not impressed by this change. [PEP-8 says](https://peps.python.org/pep-0008/#descriptive-naming-styles):

> Note: When using acronyms in CapWords, capitalize all the letters of the acronym. Thus HTTPServerError is better than HttpServerError.

Meanwhile, this is a hard-breaking change for anyone who uses `mistletoe.HTMLRenderer` rather than `mistletoe.html_renderer.HTMLRenderer`.

**Comment by pbodnar** [comment]
@pydsigner, thanks for letting us know and sorry for the inconvenience! I have just released v1.2.1 where `mistletoe.HTMLRenderer` should work again.

Regarding the change to "strict PascalCase" itself, you are right that PEP-8 suggests the other way. AFAIK in C-style languages, `HtmlRenderer` is the recommended way to go (see e.g. [here](https://stackoverflow.com/questions/2853531/how-do-you-pep-8-name-a-class-whose-name-is-an-acronym/2853590#2853590)), even if there is just one acronym in the name. But I'm not _strictly_ against returning to the PEP-8 style, provided it will be requested by the mistletoe community...
