### ISSUE TITLE
Invalid code blocks rendering with comments

### ISSUE THREAD

**Issue by sdispater** [miyuchina/mistletoe#2]
First of all, thanks for your library :-)

I found a bug regarding code blocks rendering.

If you have comments (starting with `#`) in a code block, it will not be rendered properly.

```markdown
# Title

​​​​```python
# Some comment
foo = 'bar'
​​​​```
```

will be rendered as

```html
<h1>Title</h1>
<p><code>`</code>python # Some comment</p>
<p>foo = &#x27;bar&#x27; <code>`</code></p>
```

However without the comment, it's rendered properly

```html
<h1>Title</h1>
<pre>
<code class="lang-python">
foo = &#x27;bar&#x27;
</code>
</pre>
```

**Comment by miyuchina** [comment]
Thanks for this--should be fixed now. Typing your example into mistletoe yields:

```html
<h1>Title</h1>
<pre>
<code class="lang-python">
# some comment
foo = &#x27;bar&#x27;
</code>
</pre>
```

**Comment by sdispater** [comment]
Thanks for the quick fix 😃
