### ISSUE TITLE
Delete a Document node. Recommended way?

### ISSUE THREAD

**Issue by 4l1fe** [miyuchina/mistletoe#209]
Sadly, after searching the subject i didn't find a way of how i could drop a few nodes while modifying `Document` for further rendering it back to markdown.

Pls suggest an idea. I see [the example](https://github.com/miyuchina/mistletoe/blob/master/dev-guide.md) of editing node content, but deleting tree nodes is somewhat more complex and i'm not sure that it can be done by **mistletoe**

**Comment by pbodnar** [comment]
Hi @4l1fe, in mistletoe, deleting tree nodes before rendering should be easy - you just need to update the `children` _attribute_ (possibly a _property_ soon - see #206)  of the token you want to modify, see e.g. [here](https://stackoverflow.com/questions/1207406/how-to-remove-items-from-a-list-while-iterating/1207461#1207461) for inspiration. Mistletoe currently doesn't have any API for handling operations like these _explicitly_.

**Comment by 4l1fe** [comment]
Do you think deleting nodes while traversing a tree with [utils.traverse](https://github.com/miyuchina/mistletoe/blob/b911e5b64a98d537bb44a0212cbf8fa708d37d48/mistletoe/utils.py#L6) is safe?

**Comment by pbodnar** [comment]
Well, I think that if you manage to modify the `children` of a yielded `TraverseResult.node`, nothing bad will happen - the newly assigned child nodes will just be iterated thereafter by the `traverse()` function. Right?

**Comment by 4l1fe** [comment]
> I think that if you manage to modify the `children` of a yielded `TraverseResult.node`

I'm doing exactly this way, all is ok at the moment,but it is somewhat like modifing a list while iterating it that is unsafe in general.

Anyway, thx for your opinion.
