### ISSUE TITLE
Mistletoe plant and logo 

### ISSUE THREAD

**Issue by liuq** [miyuchina/mistletoe#21]
Hi,

first of all, thanks for the tool: it's a piece of cake for markdown parsing (and also for custom rendering)!

Just for the sake of precision, I'd like to point out a common misconception about mistletoe, which is not the plant depicted in the logo. The plant of the logo is either the [Ruscus aculeatus](https://en.wikipedia.org/wiki/), also called *butcher's-broom* or *christmas berry* or the [Ilex aquifolium](https://en.wikipedia.org/wiki/Ilex_aquifolium), called *christmas holly*. Instead, the **mistletoe** is the [Viscum album](https://en.wikipedia.org/wiki/Mistletoe), which has white berries and plain thick leaves (not spiny as the other two plants).

I'd like also to make clear that letting you change the logo is not my purpose, but I want only to friendly make you aware of which is the *“right“* **mistletoe**. :-)

All the best,

Luca

**Comment by liuq** [comment]
As I mention, I'd just want to let you know about, so I close the issue ;-)

**Comment by miyuchina** [comment]
Wow, I had no idea! Thank you for pointing this out!

I wonder if we could find a cartoon-ish logo that is similar in style to the current one, but is of the actual mistletoe plant. I'll keep an eye out for it, but let me know if you see a good one!

**Comment by miyuchina** [comment]
I'm reopening this issue to address the new logo suggested in @liuq 's pull request #23. The new file is [here](https://github.com/miyuchina/mistletoe/pull/23/commits/55b22f802533bc256504d28b64745a521772b926) if anyone's interested.

My tentative decision on this is as follows:

1. Leave this issue open for now and see if others have thoughts about the logo change;
2. This is a purely subjective issue, but I'll go look for one that is closer to the current art style (rounder shapes and lines, etc.,) and I'll record my findings here;
3. Regardless of whether I find another logo, I'll consider changing it in the next major version release.

I don't have a timeframe for the next major release, but I suspect it's gonna take a bit before I get around to it. Let me know if this is not okay!

**Comment by miyuchina** [comment]
I found [this](https://www.flaticon.com/free-icon/mistletoe_616034) one, which is kind of similar to the one @liuq posted? Looks like it doesn't have berries. Just want to make sure this is a real mistletoe.

**Comment by liuq** [comment]
Yes it is (besides the berries, indeed).

**Comment by aoloe** [comment]
hi

i'm currently working on a markdown library in c++ that is very much inspired by your work and i took the name.

i don't know yet, if i can bring it to a state where it's really usable in production, but it's gently evolving and i'm pretty happy with the result until now!

now, if you prefer not to use @liuq 's logo in its current state, i would be glad to use it myself (without the ribbon... ehm ehm...)
i really like it!

anyway, thank you for all the work you did in mistletoe, it really helped me!
and -- since i'm learning both python and c++ -- it was fun to see what i had to and what i could do differently in c++!

**Comment by miyuchina** [comment]
@aoloe Do go ahead and use it! I'm glad you find mistletoe helpful. Best of luck with your library!

**Comment by aoloe** [comment]
thanks! i'll will get in touch with @liuq and get his aproval... : - )

**Comment by miyuchina** [comment]
Updated logo in version 0.6. Thanks!
