### ISSUE TITLE
Thematic break not being detected

### ISSUE THREAD

**Issue by yelboudouri** [miyuchina/mistletoe#232]
Hello, the tokenizer doesn't recognize the thematic break in this case:

```python
msg = """Hi
---
hi
---
"""
```

Do you see any reason why? I reviewed the code but couldn't find any obvious issues.

**Comment by pbodnar** [comment]
Hi @yelboudouri, by putting `---` right below a text, you actually say the text is a 2nd-level heading (`<h2>`). By separating it by _a blank line_, you can make it a thematic break.

You can check it out here on GitHub as well and you'll get the same results.

**Comment by yelboudouri** [comment]
No, even with the GitHub preview, it shows two thematic breaks.

**Comment by pbodnar** [comment]
Not for me. Example:

a) without blank lines (`<h2>` headings with CSS-based underline != thematic breaks):

Hi
---
hi
---

b) with blanks lines (paragraphs and thematic breaks):

Hi

---

hi

---
