### ISSUE TITLE
Feature request: Less strict table parsing

### ISSUE THREAD

**Issue by huettenhain** [miyuchina/mistletoe#26]
Hey there! 
To get the following table:

Column1 | Column2
------: | :------
   Data | Data
   Data | Data

the Mistletoe parser would require the following code:
```
| Column1 | Column2 |
| ------: | :------ |
|    Data | Data    |
|    Data | Data    |
```

Many Markdown implementations I know allow the following:
```
| Column1 | Column2
| ------: | :------
|    Data | Data
|    Data | Data
```
and in fact, while typing this, I figured out that Github will even parse the following:
```
Column1 | Column2
------: | :------
   Data | Data
   Data | Data
```
I don't see a particular use for the latter, but the first one has often made it much easier for me to maintain visually appealing, ASCII-formatted tables where the last column contains content of very different lengths.

Would it be easy for mistletoe to support this as well? @miyuchina If this is not out of scope but you are busy, I can also try implementing this myself.

**Comment by miyuchina** [comment]
I didn't know this was possible! I don't think this is out of scope, and since CommonMark does not even support tables, we might as well do as we please, and make the syntax easier to write in :smiley:

I think if I were to do it, I should be able to get around to this in about a week, and I'll do another release to pypi after that. Would that be soon enough?

**Comment by miyuchina** [comment]
Feature added in 566b234. Currently the shorthand form for tables still require a delimiter row. For, example, this is **not** a valid table:

```markdown
00 | 01
10 | 11
```

But this is a table:

```markdown
00  | 01
--- | ---
10  | 11
```

The reason for this is that the `|` character is still commonly used inline, and allowing tables without delimiter rows might cause many normal lines to be accidentally parsed as tables. (GFM, I noticed, also needs the delimiter row.)

@huettenhain What do you think?

**Comment by huettenhain** [comment]
Fantastic! That was incredibly fast :smile:
