### ISSUE TITLE
Tiny followup on table shorthands

### ISSUE THREAD

**Issue by huettenhain** [miyuchina/mistletoe#29]
I think a bug might have been introduced in 566b234b540bb926a547f79edb8017a78cd83397: Consider the following table:

    ### Test

     One | Two
     --- | ---
     A   | BC
     D   | ED

When I translate it to Jira, I get the following:

    h3. Test
    ||A||B||
    |A|B|
    |D|E|

It seems to have removed the last character in every row because I left out the closing bar.

**Comment by miyuchina** [comment]
Should be fixed in 527943f; I forgot to update the `TableRow` class accordingly. Thank you!

**Comment by huettenhain** [comment]
as always, thanks to *you* for the incredibly swift response.
