### ISSUE TITLE
SpanToken.Image regex does not allow empty alt text 

### ISSUE THREAD

**Issue by joncass** [miyuchina/mistletoe#33]
The Image SpanToken does not allow empty alt text, so `![](some/image.png)` will not be parsed. I think the regex [here](https://github.com/miyuchina/mistletoe/blob/master/mistletoe/span_token.py#L144) needs to be updated.

P.S. Thanks for writing Mistletoe - it is great so far! :)

**Comment by miyuchina** [comment]
Updated in 25cbccb, and will be included in the next release. Thanks a lot!

**Comment by joncass** [comment]
Awesome - thanks for the speedy reply! Do you know when the next release will be?

**Comment by joncass** [comment]
No that's great. If it was going to be months I'd probably pull my own copy, but a week or two is fine :). Thanks again!
