### ISSUE TITLE
Syntaxe highlight support via Pygments

### ISSUE THREAD

**Issue by Bridouz** [miyuchina/mistletoe#35]
Hi,

Is there a possibility to use **Pygments** with Mistletoe to provide syntaxe highlighting to the markdown renderer ?

**Comment by miyuchina** [comment]
Hello there!

To clarify: would you want something similar to [this renderer feature](https://github.com/lepture/mistune#renderer) in mistune, where code blocks can be highlighted with Pygments? or would you want to only use mistletoe as a lexer, and use Pygments' renderer frontend completely?

Both (I think) can be done. The first one shouldn't be hard, and the second one looks like a fun exploratory project for the weekend. Let me know which one!

**Comment by miyuchina** [comment]
I added a `PygmentsRenderer` under the [contrib](https://github.com/miyuchina/mistletoe/blob/dev/contrib/pygments_renderer.py) directory that should do what you want. The code is fairly minimum, but let me know if I'm missing any features you'd like to see.

To use it in the command line, make sure `path.to.pygments_renderer` is importable by Python, and run:
```sh
mistletoe -r path.to.pygments_renderer.PygmentsRenderer some.md > out.html
```
The result will be in `out.html`.

**Comment by Bridouz** [comment]
Thanks a lot.

As I'm a non-dev trying to fill his passion for tech by learning python I wonder how I can use it in a script I'm working on to build a static blog.

I used mistune with

```
Class Mycustomrenderer(MistuneRenderer)
    Blablabla

renderer = Mycustomrenderer
md = mistune.markdown(renderer=renderer)
```

Is it possible to do the same with **Mistletoe** ?

Thanks

**Comment by miyuchina** [comment]
Yes! Just change mistune to mistletoe, and you're ready to go:

```python
class PygmentsRenderer(HTMLRenderer):
    ...

md = mistletoe.markdown(['# heading\n', 'paragraph\n'], renderer=PygmentsRenderer)
print(md) # <h1>heading</h1><p>paragraph</p>
```

**Comment by Bridouz** [comment]
Thanks a lot, it's really nice to use *Mistletoe*. Fast, simple and clean rendering.

:smile:
