### ISSUE TITLE
Heading within paragraphs are not recognized

### ISSUE THREAD

**Issue by joncass** [miyuchina/mistletoe#36]
It appears that many of the tests in the commonmark suite are failing. The one I'm particularly interested in right now is "example 48":
```
Foo bar
# baz
Bar foo
```

should get translated to

```
<p>Foo bar</p>
<h1>baz</h1>
<p>Bar foo</p>
```

but instead becomes

```
<p>Foo bar
# baz
Bar foo</p>
```

Are there any plans to fix this and/or the other failing commonmark tests?

Thanks!

**Comment by miyuchina** [comment]
Just pushed a fix for this in dbd45a0.

And yes, I do intend on fixing more of the Commonmark tests (see #17), but it is quite a hefty project, so at the moment I'm prioritizing specs that people care about, like this one. There will hopefully be more fixes coming in the summer when I'm less busy.

I do strive to fix bug reports quickly, though, so if you're annoyed by something that is in the spec but is not in mistletoe, let me know and I'll see what I can do!

**Comment by joncass** [comment]
Wow - thanks for the incredibly fast fix!

Makes sense to go through the Commonmark spec slowly, but prioritize fixes for things that people ask about. I likely have another couple incoming pretty soon :).

Do you have a regular "release" schedule?

**Comment by miyuchina** [comment]
Haha, I was just working on a related refactoring that made this fix pretty easy :) Keep the issues coming!

I don't really have a release schedule, though I usually do a release after I accumulate ~15 commits from the previous version. Bug fixes get priority, of course, and can shift releases forward. For this one I'm aiming to doing a release this coming Sunday.

**Comment by joncass** [comment]
Got it - thanks for the info.
