### ISSUE TITLE
Newlines are inserted into code tags

### ISSUE THREAD

**Issue by joncass** [miyuchina/mistletoe#38]
Parsing
`` `x=1` ``
yields
```
<code>
x=1
</code>
```
but the newline between the `x=1` and the `</code>` means that when the HTML is rendered, there is a space (i.e. it looks like `x=1[SPACE]`).

**Comment by miyuchina** [comment]
I'm not sure I can reproduce this bug regarding inline code. Here's what I'm seeing:

```html
>>> `x=1`
...
<p><code>x=1</code>
</p>
```

The newlines do get attached to the end of a code block, however. In the previous version:

```html
>>> ```
... x=1
... ```
...
<pre><code>x=1
</code></pre>
```

After 129aff4:

```html
>>> ```
... x=1
... ```
...
<pre><code>x=1</code></pre>
```

Could I bother you to confirm the inline code issue?

**Comment by joncass** [comment]
I'm unable to reproduce both this and #39 when using `mistletoe` in isolation, but can still reproduce both of them in my script (which sits on top of `mistletoe`). So probably not your problem. Sorry for the false alarm!
