### ISSUE TITLE
List parsing fails if sub list changes leader

### ISSUE THREAD

**Issue by JBartlett86** [miyuchina/mistletoe#42]
Hi,

There appears to be a bug parsing lists where sublists change the leader character.

For instance when trying to parse markdown that looks like this;

```
+ test
+ test
    - test
+ test
```

or 

```
+ test
+ test
    1. test
+ test
```

I get the following error;

\lib\site-packages\mistletoe\__init__.py:19: in markdown
    return renderer.render(Document(iterable))
\lib\site-packages\mistletoe\block_token.py:117: in __init__
    self._children = tuple(tokenize(lines, root=self))
/lib\site-packages\mistletoe\block_tokenizer.py:61: in tokenize
    token = token_type(token_type.read(lines))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = <mistletoe.block_token.List object at 0x0422D5D0>, items = []
    def __init__(self, items):
        self._children = items
        self.loose = self.__class__.loose
>       leader = self.children[0].leader
E       IndexError: list index out of range

I believe this may have been introduced in the recent changes to the list parsing functionality as I'm sure this worked previously.

Thanks,
John

**Comment by miyuchina** [comment]
Ah, some class variable related bug. Should be fixed in the latest commit; release coming within the next week or so.

Thanks a lot!
