### ISSUE TITLE
Sublists cause additional paragraph to be inserted into list

### ISSUE THREAD

**Issue by huettenhain** [miyuchina/mistletoe#44]
Consider the following example:

    mistletoe [version 0.6] (interactive)
    Type Ctrl-D to complete input, or Ctrl-C to exit.
    >>> - item a
    ...   - subitem 1
    ...   - subitem 2
    ... - item b
    ... - item c
    <ul>
    <li><p>item a</p>
    <ul>
    <li>subitem 1</li>
    <li>subitem 2</li>
    </ul>
    </li>
    <li>item b</li>
    <li>item c</li>
    </ul>

I think `item a` should not be contained in a separate paragraph, and [common mark also doesn't create a paragraph here](https://spec.commonmark.org/dingus/?text=-%20item%20a%0A%20%20-%20subitem%201%0A%20%20-%20subitem%202%0A-%20item%20b%0A-%20item%20c%0A).

**Comment by miyuchina** [comment]
Hmm, so the example is working now:

```html
mistletoe [version 0.6.1] (interactive)
Type Ctrl-D to complete input, or Ctrl-C to exit.
>>> - item a
...   - subitem 1
...   - subitem 2
... - item b
... - item c
...
<ul>
<li>item a
<ul>
<li>subitem 1
</li>
<li>subitem 2
</li>
</ul>
</li>
<li>item b
</li>
<li>item c
</li>
</ul>
```

But the loose list / tight list thing is not completely spec compliant, and requires more thought. I'll leave this issue open until I can resolve this.

**Comment by huettenhain** [comment]
Also, you are on 0.6.1 which I think is the dev branch - I was on 0.6. I checked it on dev and indeed, I get the same version number and the same behavior as you do. You can close this out whenever you like.

**Comment by miyuchina** [comment]
Oh I fixed it on the dev branch because you posted this issue--sorry that wasn't clear!

**Comment by huettenhain** [comment]
Oh! Well in that case, thank you! :smile:  I was afraid that I hat tested on the wrong branch is all.

**Comment by miyuchina** [comment]
I found a better solution. The output of the example above does not change, but it handles other corner cases better. Closing this issue for now!
