### ISSUE TITLE
Token precendence

### ISSUE THREAD

**Issue by joncass** [miyuchina/mistletoe#45]
I'm having difficulty with token precendence. In particular, I'm writing a `Renderer` that extends from `HTMLRenderer`, but I'd like to parse markdown inside of `<aside>` tags (i.e. `<aside>*foo*</aside>` would become `<aside><strong>foo</strong></aside>`). So I was hoping to write a custom token that would detect `aside`s and `render_inner` on it. My custom token doesn't trigger though, because the `<aside> *foo* </aside>` is matched by the existing mistletoe HTML tokens first. I even tried overriding `_tokens_from_module` so that I could change the order of the tokens but that didn't seem to help.

Any ideas on how I could accomplish this?

Thanks!

**Comment by miyuchina** [comment]
I played with it a little, and perhaps this is what's going on. Using this code:

```python
class Aside(SpanToken):
    pattern = re.compile(r"<aside>(.+?)</aside>")

class CustomRenderer(HTMLRenderer):
    def __init__(self):
        super().__init__(Aside)

    def render_aside(self, token):
        return '<aside>{}</aside>'.format(self.render_inner(token))
```

I can render:

```markdown
bar <aside>*foo*</aside>
```

to:

```html
<p>bar <aside><em>foo</em></aside></p>
```

But this markdown snippet will not render the inner emphasis:

```markdown
<aside>*foo*</aside>
```

Because the entire block is first captured by the `HTMLBlock` token. To get around this, you need to define both a block-level aside tag and a span-level one, and pass both of them into the `super` constructor. Something like:

```python
from mistletoe.span_token import tokenize_inner

class AsideBlock(BlockToken):
    def __init__(self, lines):
        lines[0].replace('<aside>', '')
        lines[-1].replace('</aside>', '')
        super().__init__(''.join(lines), tokenize_inner)

    @classmethod
    def start(cls, line):
        return line.lstrip().startswith('<aside>')

    @classmethod
    def read(cls, lines):
        line_buffer = []
        for line in lines:
            line_buffer.append(line)
            if line.rstrip().endswith('</aside>') or line == '\n':
                break
        return line_buffer
```

By the way, rendering the inner elements of `HTMLSpan` should also be the standard behavior, and I'll probably add it soon. Let me know if there're any further questions!

**Comment by joncass** [comment]
Cool, this works. (Note: I did have to modify the `AsideBlock` init function a bit since strings are immutable so `lines[0].replace` returns a string but doesn't modify the given one). Thanks!

In terms of making it the default behavior to render inner elements, do you think you'd do that for both `HTMLSpan` and `HTMLBlock` or just one of them? I went back and forth on whether I wanted to do this for all elements or not - I think it probably makes sense, though I don't think it's strictly commonmark compliant.

**Comment by miyuchina** [comment]
I think I'm doing that only for `HTMLSpan` and not for `HTMLBlock`, in accordance with CommonMark. The interesting thing is that CommonMark has some pretty particular definitions for `HTMLBlock`. Using these definitions, I think not rendering inner elements for `HTMLBlock` would be following the rule of least surprises. You can take a look at [Section 4.6](https://spec.commonmark.org/0.28/#html-blocks) in the spec in case you're interested.

Sorry for the late response! I'm closing the issue, but feel free to comment further.
