### ISSUE TITLE
Only the fist inline code element is  rendered in version 0.7

### ISSUE THREAD

**Issue by huettenhain** [miyuchina/mistletoe#50]
I am encountering an odd quirk in mistletoe 0.7:

    C:\> mistletoe
    [warning] readline library not available.
    mistletoe [version 0.7] (interactive)
    Type Ctrl-D to complete input, or Ctrl-C to exit.
    >>> This `code` and this `code` should all be `code`
    ... ^Z

    <p>This <code>code</code> and this `code` should all be `code`</p>
    >>>

As always, thanks a lot for the great library.

**Comment by miyuchina** [comment]
Should be fixed in 11ac586!

```html
>>> This `code` and this `code` should all be `code`
...
<p>This <code>code</code> and this <code>code</code> should all be <code>code</code></p>
```

I'll do another release this coming weekend.
