### ISSUE TITLE
StopIteration Exception without terminating newlines

### ISSUE THREAD

**Issue by rsrdesarrollo** [miyuchina/mistletoe#52]
Hi

This simple test raises an StopIteration Exception on block_tokenizer.

```
mistletoe.markdown('[text](http://example.com)')
```

I think it is related with the lack of end-of-line at the end.

**Comment by miyuchina** [comment]
Related to #51, should be fixed in 1a43a68ce6c9a2161b4ba9fcfc1068e3eb754def!
