### ISSUE TITLE
lists should not contain <p>

### ISSUE THREAD

**Issue by jcheger** [miyuchina/mistletoe#54]
Why do you use &lt;p&gt;&lt;/p&gt; in lists ? This is not the way Commonmark does it.

Other strange behavior: in the same document, some lists get the paragraphs, some others don't. Could you explain how it is supposed to work ?

**Comment by miyuchina** [comment]
Hi there!

According to [CommonMark](https://spec.commonmark.org/0.28/#loose):

> A list is loose if any of its constituent list items are separated by blank lines, or if any of its constituent list items directly contain two block-level elements with a blank line between them. Otherwise a list is tight. (The difference in HTML output is that paragraphs in a loose list are wrapped in `<p>` tags, while paragraphs in a tight list are not.)

So:

```markdown
- a
- b

- c
```

... will be rendered to:

```html
<ul>
<li>
<p>a</p>
</li>
<li>
<p>b</p>
</li>
<li>
<p>c</p>
</li>
</ul>
```

And:

```markdown
- a
- b
- c
```

... will be rendered to:

```html
<ul>
<li>a</li>
<li>b</li>
<li>c</li>
</ul>
```

Can you attach the wrong example you're seeing?

**Comment by jcheger** [comment]
I did revert my code to use markdown, that does not have this behavior.
But, in deed, the last block list is right, but all the ones before get paragraphs.

Example:

```
## heading 1

* a
* b 
* c

## heading 2

* d
* e
* f

## heading 3

* g
* h
* i
```

Block 1 and 2 get paragraphs, and block 3 (last one) is ok.
