### ISSUE TITLE
Specify initial header level on HTML output

### ISSUE THREAD

**Issue by nosammai** [miyuchina/mistletoe#55]
Hi,

Sorry if this is a silly question, but I'm trying to parse some markdown and embed it as html inside of a page on my web application. This page already has a couple levels of Header tags, so I'd like for the headings inside the markdown to start at \<h3\> rather than \<h1\>. Is it possible to pass in an initial header level to the HTMLRenderer?

Thanks!

**Comment by miyuchina** [comment]
Hey! Not stupid at all, although it is going to be slightly more complicated than passing in a value. Something like this will do:

```python
class MyRenderer(HTMLRenderer):
    def render_heading(self, token):
        template = '<h{level}>{inner}</h{level}>'
        inner = self.render_inner(token)
        return template.format(level=token.level+2, inner=inner)
```

... and you can use `MyRenderer` just like `HTMLRenderer`.

Let me know if you have more questions!

**Comment by nosammai** [comment]
Awesome, that worked great. Thank you!
