### ISSUE TITLE
Unexpected Paragraph Tag in Lists

### ISSUE THREAD

**Issue by href** [miyuchina/mistletoe#65]
When using an ordered and an unordered list in a single markdown, unexpected paragraphs are used inside the list items:

```python
from mistletoe import markdown
markdown('* foo\n\n1. bar')
```
Result:
```html
<ul>
    <li>
        <p>foo</p>
    <li>
</ul>
<ol>
    <li>bar</li>
</ol>
```

If the lists are rendered separately, no paragraph is used. Almost looks like there exists some shared state.

**Comment by miyuchina** [comment]
Should be fixed by 5191b42.
