### ISSUE TITLE
how to add “target="_blank" to link 

### ISSUE THREAD

**Issue by find456789** [miyuchina/mistletoe#84]
how to add `target="_blank` to link 

when i add a href `https://github.com/miyuchina/mistletoe`

i got `<a href="https://github.com/miyuchina/mistletoe" rel="nofollow">https://github.com/miyuchina/mistletoe</a>`

---

i hope i got `<a href="https://github.com/miyuchina/mistletoe" rel="nofollow" target="_blank>https://github.com/miyuchina/mistletoe</a>`

 **target="_blank**

**Comment by Rogdham** [comment]
Try overriding the `render_link` and `render_auto_link` (that one is for `<https://example.com/>`) methods in a new renderer.

Something like this:
```py
import re

from mistletoe import markdown, HTMLRenderer


class BlankLinkHTMLRenderer(HTMLRenderer):
    @staticmethod
    def add_blank(html):
        return re.sub("^<a ", '<a target="_blank" ', html)

    def render_link(self, token):
        html = super().render_link(token)
        return self.add_blank(html)

    def render_auto_link(self, token):
        html = super().render_link(token)
        return self.add_blank(html)


md = "Foo [example](https://example.com) bar"
html = markdown(md, BlankLinkHTMLRenderer)
print(html)  # <p>Foo <a target="_blank" href="https://example.com">example</a> bar</p>
```

**Comment by find456789** [comment]
@Rogdham

  thank you very much
