### ISSUE TITLE
Pass custom renderer via cli

### ISSUE THREAD

**Issue by lastcoolnameleft** [miyuchina/mistletoe#9]
Looking at https://github.com/miyuchina/mistletoe/blob/master/mistletoe/convert.py#L19

It appears that running mistletoe CLI parses to markdown by default.  It would be helpful to provide custom renderers at runtime.

Cheers,
-Tommy.

**Comment by miyuchina** [comment]
Feature added in 427c7d3.

Usage:

```sh
mistletoe foo.md --renderer custom_renderer.CustomRenderer
```

Thanks @lastcoolnameleft !

**Comment by lastcoolnameleft** [comment]
You’re welcome. And thank you as this made my debugging and experimenting a lot easier.

**Comment by miyuchina** [comment]
You would be happy to learn that if you just pass in the custom renderer flag without a file name, mistletoe will open interactive mode with that renderer. Just added earlier today in bac53767 !

**Comment by lastcoolnameleft** [comment]
Good to know. Thanks!
