### ISSUE TITLE
A book publishing project interested in helping out w/ Mistletoe

### ISSUE THREAD

**Issue by choldgraf** [miyuchina/mistletoe#92]
Hey there @miyuchina 👋  - I wanted to introduce myself and a team that I am working with.

We are a group of academic researchers who are working on a tech stack to build open, reproducible documents with Python. We've been doing a survey of the Markdown landscape in Python, and think that Mistletoe is a really nice balance between clean design, performance, extensibility, and adherence to the CommonMark standard.

We're going to use Mistletoe as the core of our markdown parser, and plan to write our own extensions to extend the syntax. There might be a few things here and there that we'd like to improve, so I wanted to let you know that a few PRs might be coming from our team.

In case you'd like to check out what we are up to, we've set up a github organization to host the projects that we're working on as a part of this project: https://github.com/ExecutableBookProject

It would be great to know your plans around Mistletoe, and if you're interested in us improving things a bit (it would be things like minor features, improvements to testing, etc). If you'd like to chat, we'd be happy to do so!

thanks again for this great project!

**Comment by chrisjsewell** [comment]
FYI we ended up creating a seperate fork of this https://mistletoe-ebp.readthedocs.io, but now have actually moved to using https://github.com/executablebooks/markdown-it-py
