### ISSUE TITLE
Change html output for a paragraph

### ISSUE THREAD

**Issue by eimfach** [miyuchina/mistletoe#95]
Hey there,

Is it possible to change the output for a paragraph from a `p` tag to `blockquote` tag ?

For example, I have this markdown line:

`Lorem ipsum solor dit amed`

Mistletoe wraps this in a `p` tag, but I want a blockquote.

is this possible ? Also, how could I add css classes to the blockquote ?

Thanks !

**Comment by anderskaplan** [comment]
Hi @eimfach, the way to represent a blockquote in Markdown is with the greater-than sign, like this:
`>Lorem ipsum solor dit amed`

which will be rendered as:
>Lorem ipsum solor dit amed

**Comment by pbodnar** [comment]
It looks like the question was answered. Thank you. :)
